### ISSUE TITLE
Unbind the documentation from distutils

### ISSUE THREAD

**Issue by arhadthedev** [arhadthedev/cpython#9]
https://github.com/python/cpython/issues/85454#issuecomment-1184756184:

> If you like to help, then you could start with updating our documentation. You could update the "distributing" section to refer to setuptools and PyPA packaging instead of distutils. There are also references to :mod:\`distutils\` and various functions in the distutils namespace in the whatsnew. They have to be replaced by \`\`distutils\`\`, too.

It gives the following targets:

- [ ] Replace `distutils`-based documentation with `setuptools`-based one (TBD).
- [x] Replace <code>:mod:\`distutils\`</code> with <code>\`\`distutils\`\`</code> (https://github.com/python/cpython/pull/95192)

**Comment by merwok** [comment]
> Replace distutils-based documentation with setuptools-based one (TBD).

Do you mean making very short documents that point to setuptools / packaging docs, or rewriting docs in CPython repo with lots of setuptools specifics?

**Comment by arhadthedev** [comment]
I planned to use the second approach since small hyperlinked chunks are hard to read. However, I need to educate myself on how setuptools work in the first place (if the rewriting issue is of a low priority), or give it up to someone with packaging experience if it's more urgent.

**Comment by merwok** [comment]
I don’t think CPython docs should be full of info referencing a third-party project.
I would keep the files (because of all the existing links that point there), include a disclaimer about distutils being removed, and link to packaging.python.org and sometimes maybe setutpools docs.

This may need a discussion with a bigger audience on python-dev or packaging discuss.

**Comment by arhadthedev** [comment]
The setuptools references seem to be addressed by Christian in https://github.com/python/cpython/pull/95239 and pending PRs (`Some examples like zipapp need to be updated later.`). Closing as done on my side.
